### ISSUE TITLE
Enhancement: Switch off Printer after a job

### ISSUE THREAD

**Issue by Dedcap** [ralmn/OctoPrint-Ikea-tradfri#38] opened 2021-02-11 10:35 UTC
The plugin is working fine and I would like to make a request to have the capacity to ask to switch off the printer at the end of a job when the temperature have been back to normal
I heard that some plugin like tp-link are capable of such magic ;)

**Comment by ralmn** [comment] 2021-02-14 13:19
Duplicate of #22

**Closed as completed by ralmn** 2021-02-14 13:19 UTC
